### ISSUE TITLE
Downloads randomly stop

### ISSUE THREAD

**Issue by j0lol** [catlinman/campdown#5]
Keep getting this error
```
The download didn't complete. Attempting 1 of 2 retries.
Waiting for 30 seconds ...
Traceback (most recent call last):
  File "/usr/bin/campdown", line 11, in <module>
    load_entry_point('campdown==1.46', 'console_scripts', 'campdown')()
  File "/usr/lib/python3.8/site-packages/campdown/__init__.py", line 69, in cli
    downloader.run()
  File "/usr/lib/python3.8/site-packages/campdown/__init__.py", line 220, in run
    page.fetch_download()  # Begin the download process.
  File "/usr/lib/python3.8/site-packages/campdown/discography.py", line 263, in fetch_download
    self.queue[i].download()
  File "/usr/lib/python3.8/site-packages/campdown/album.py", line 244, in download
    s = download_file(self.art_url, self.output,
  File "/usr/lib/python3.8/site-packages/campdown/helpers.py", line 350, in download_file
    for chunk in response.iter_content(chunk_size=block_size):
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 769, in iter_content
    raise StreamConsumedError()
requests.exceptions.StreamConsumedError
```

**Comment by zealsprince** [comment]
Which Bandcamp page is this failing on for you? I'm currently developing a new version that should release this weekend that fixes a few issues with some specific pages so maybe the one you're trying is also affected!

**Comment by j0lol** [comment]
Sorry for taking so long to reply, i seem to get it on pretty much every download randomly, but it only seems to happen often when downloading discographies from bandcamp

**Comment by zealsprince** [comment]
Check if the new update fixed things! You can download the newest version via the following command:

`pip install campdown --upgrade --user`

Give me a shout if things are still borked. In that case I'll go a little more in-depth on the troubleshooting.
